# Site settings
title: BK Services
email: bkservices@bkservices.com
description: > # this means to ignore newlines until "baseurl:"
  BK Services Description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bkservices.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
